# Set shell
set-option -g default-shell /usr/bin/zsh

# Rebind: <prefix> | and - for splits
unbind '"'
unbind %
bind -n M-| split-window -h -c "#{pane_current_path}"
bind -n M-_ split-window -v -c "#{pane_current_path}"

# No-prefix (root table) bindings — Alt+arrow to switch panes
bind -n M-Left  select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up    select-pane -U
bind -n M-Down  select-pane -D

# Ctrl+Alt to switch windows
bind -n C-M-Right next-window
bind -n C-M-Left  previous-window

# Scroll
set -g mouse on
set -g history-limit 50000

# Clipoard support
set -s set-clipboard on
set -as terminal-features ',*:clipboard'
set -g default-terminal 'tmux-256color'

# Drag = select only, don't copy, don't exit copy mode
unbind -T copy-mode-vi MouseDragEnd1Pane
unbind -T copy-mode    MouseDragEnd1Pane
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X stop-selection
bind -T copy-mode    MouseDragEnd1Pane send-keys -X stop-selection

# Explicit copy
bind -T copy-mode-vi C-S-c send-keys -X copy-selection-and-cancel
bind -T copy-mode    C-S-c send-keys -X copy-selection-and-cancel

# Any key exits copy mode
run-shell "bash ~/.config/tmux/utilities/exit-copy-mode.sh"

# Theme
set -g @tmux_power_theme 'moon'

set -g @tmux_power_right_x '#(~/.config/tmux/utilities/tmux-netspeed.sh 󰇚 󰕒)'

set -g @tmux_power_prefix_highlight_pos 'L'

set -g @tmux_power_right_w '#(tmux-mem-cpu-load)'

run-shell "~/.config/tmux/tmux-power/tmux-power.tmux"

# TPM
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'
#set -g @plugin 'wfxr/tmux-net-speed'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'thewtex/tmux-mem-cpu-load'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
